version: 2
project_name: clearvault

before:
    hooks:
        - go mod tidy

builds:
    - id: clearvault
      main: ./cmd/clearvault
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s -w

    - id: clearvault-fuse
      main: ./cmd/clearvault
      env:
          - CGO_ENABLED=1
      tags:
          - fuse
          - fuse3
      goos:
          - linux
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s -w
      overrides:
        - goos: linux
          goarch: arm64
          env:
            - CGO_ENABLED=1
            - CC=aarch64-linux-gnu-gcc

archives:
    - id: clearvault
      builds:
          - clearvault
      format: tar.gz
      name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
      format_overrides:
          - goos: windows
            format: zip

    - id: clearvault-fuse
      builds:
          - clearvault-fuse
      format: tar.gz
      name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_fuse'

checksum:
    name_template: "checksums.txt"

changelog:
    use: git
